### PR TITLE
implement Hexadecimal #15

### PR DESCRIPTION
**Pull request by 0xWaleed**
hexadecimal implementation using string operation. 
I am not sure if this solve the problem because the issue has no details

### CODE REVIEW

**Comment by DanielRomeo** [comment]
Hey @0xWaleed, I just went through your PR commits, it seems you have called the "decimal function" to convert the hex number to decimal. Unfortunately his is not allowed. The whole point of this project is to write the  actual algorithm ourselves.
please read the contributing documentation [here](https://github.com/mrbrianevans/number-format-converter/blob/master/contributing.md).. more especially read the [ backend contributing documentation](https://github.com/mrbrianevans/number-format-converter/blob/master/functions/contributing.md).  These will explain what you need to do in order to contribute. 

Daniel

**Comment by 0xWaleed** [comment]
I am not sure if this ok,
```typescript

if (representation.startsWith('0x')) {
            representation = representation.substr(2)
        }
        let res = 0;
        for (const element of representation) {
            let number;
            const charCode = element.charCodeAt(0);
            if (charCode >= 48 && charCode <= 57)
            {
                 number = charCode - 48;
            }
            else
                {
                     number = charCode - 65 + 10;
                }
            res = (res << 4) | ((number) & 0xF)
        }
        return res;
```

don't worry about the code I'll clean it up, also what about 0x should be omitted ?

**Comment by DanielRomeo** [comment]
hey @0xWaleed  yes that's great. 
Also, don't forget the algo for the encode function as well :)

**Comment by DanielRomeo** [comment]
The 0x doesn't have to be omitted, its okay.

**Pull request merged**
